import Head from "next/head";

import Header from "../components/Header";

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>BeYu Labs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <div className="px-6 py-4">{children}</div>
      </main>

      {/* <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by coffee
        </a>
      </footer> */}
    </>
  );
};

export default Layout;
